### ISSUE TITLE
urllib2.HTTPError: HTTP Error 404: Object Not Found

### ISSUE THREAD

**Issue by perrfect** [jasonmcintosh/rabbitmq-zabbix#110]
Hi.
I'm using your template on my zabbix-server and in a discovery rules, when i enable "rabbitmq shovels", I have get the error:
`Traceback (most recent call last):  File "./api.py", line 285, in <module>    main()  File "./api.py", line 272, in main    print api.check_shovel(filters)  File "./api.py", line 134, in check_shovel    for shovel in self.call_api('shovels'):  File "./api.py", line 37, in call_api    return json.loads(urllib2.build_opener(handler).open(url).read())  File "/usr/lib64/python2.7/urllib2.py", line 437, in open    response = meth(req, response)  File "/usr/lib64/python2.7/urllib2.py", line 550, in http_response    'http', request, response, code, msg, hdrs)  File "/usr/lib64/python2.7/urllib2.py", line 475, in error    return self._call_chain(*args)  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain    result = func(*args)  File "/usr/lib64/python2.7/urllib2.py", line 558, in http_error_default    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)urllib2.HTTPError: HTTP Error 404: Object Not Found
-- | --`

How can i decide the problem?

**Comment by ostin654** [comment]
It is a bug, need to catch exception in check_shovel method
