### ISSUE TITLE
 api.py: error: option --check: invalid choice: '' (choose from u'list_queues', u'list_shovels', u'list_nodes', u'queues', u'shovels', u'check_aliveness', u'server')

### ISSUE THREAD

**Issue by lanyuange** [jasonmcintosh/rabbitmq-zabbix#114]
++ dirname rabbitmq-status.sh
+ cd .
+ source ./.rab.auth
++ USERNAME=zabbix
++ PASSWORD=pass
++ CONF=/etc/zabbix/zabbix_agentd.d/zabbix-rabbitmq.conf
++ LOGLEVEL=INFO
++ LOGFILE=/var/log/zabbix/rabbitmq_zabbix.log
++ PORT=15672
+ TYPE_OF_CHECK=
+ METRIC=
+ NODE=
+ [[ -z lyk-test5 ]]
+ [[ -z '' ]]
++ hostname
+ NODE=lyk-test5
+ ./api.py --hostname=lyk-test5 --username=zabbix --password=pass --check= --metric= --node=lyk-test5 --filters= --conf=/etc/zabbix/zabbix_agentd.d/zabbix-rabbitmq.conf --loglevel=INFO --logfile=/var/log/zabbix/rabbitmq_zabbix.log --port=15672 --protocol=
Usage: api.py [options]

api.py: error: option --check: invalid choice: '' (choose from u'list_queues', u'list_shovels', u'list_nodes', u'queues', u'shovels', u'check_aliveness', u'server')

**Comment by quangln94** [comment]
i have same issue. how can i fix it ?
