### ISSUE TITLE
No data for dynamic items

### ISSUE THREAD

**Issue by fwynyk** [jasonmcintosh/rabbitmq-zabbix#15]
All seems to be working, all other items (not dynamic) are working and receiving data, the host (rabbitmq) was populated with all queues available in the rabbitmq, but it didn't bring the item values for each queue. Actually, none of the dynamic itens was published in recent data. Do you have any ideias why it don't return the queue_message_stats_deliver_get and the queue_message_stats_publish?

**Comment by tandar17** [comment]
had this issue, it was due to zabbix_sender not being installed on the rabbitmq server
