### ISSUE TITLE
rabbitmq-status.sh not working

### ISSUE THREAD

**Issue by whitbrett** [jasonmcintosh/rabbitmq-zabbix#18]
First, Let me state that this is really good stuff.  I believe that I have found a issue, but need to have someone else look at it for me.

I am having issues with getting the information about the queues out of the system.  I have been tracing data all day, and here is what I can see.  I am not sure if I have this right, but it applies to the discovery rules.  

Currently, my system will query and get all the queues that are on the server.  
both list_rabbit_nodes.sh and list_rabbit_queues.sh work just fine.  They are reporting back to zabbix with no issues.

The issue is when it goes to pull the information from the server about the queues that are on the server.

I noticed that on one of the discovery trigger templates,  rabbitmq[{#VHOSTNAME},queue_messages,{#QUEUENAME}] is used to get the messages on the queue.

This will call rabbitmq-status.sh in the directory.  The issue I believe is the placing of the variables.
UserParameter=rabbitmq[*],/etc/zabbix/scripts/rabbitmq/rabbitmq-status.sh $1 $2 $3
That would put $1 = VHOST NAME, $2 = queue_messages, and $3 = the queue name.

This will then get passed to the api.py like the following:
/api.py --hostname=localhost.localdomain --username=admin --password=admin --check=vhost67.232.139.140 --metric=queue_messages --node=qi67.232.139.140radiodix --filters= --conf=/etc/zabbix/zabbix_agent.conf

Which will then return a error:

api.py: error: option --check: invalid choice: 'vhost67.232.139.140' (choose from 'list_queues', 'list_nodes', 'queues', 'check_aliveness', 'server')

First thing that I can see is that there is not check for just a vhost.  Also, there is no matric for queue_messages...

Am I missing something here...  

All I want to get is the number of messages in the queue and have a trigger on it when it goes over a number that we set.

**Comment by jasonmcintosh** [comment]
I see the confusion and I've quasi-fixed this in the latest release.  The discovery rule doesn't actually generate active or passive checks.  It generates "listeners".  Then there's a separate server item,
rabbitmq[queues]
that triggers a remote send of all current queue settings.  You can't actually call the rabbitmq-status.sh directly to get a single queue status.  You can call api.py with the appropriate calls, but all the queue checks are based on zabbix_sender sending the responses back.

The reason for this is I found performance way too slow if you don't do it as a batch check.  A few individual checks is ok, but the queue checks were taking upwards of 5 minutes (course, I've got like 4000 queues).  That hits timeouts in zabbix agents and other odd situations.

SO the equivalent to manually trigger a change is do:
./rabbitmq-status.sh queues

AND on the server side, look to make sure there aren't any errors on the "rabbitmq[queues]" check that's part of the template.

**Comment by jasonmcintosh** [comment]
Get things figured out on this?

**Comment by whitbrett** [comment]
We have had to look at doing out own implementation. 
I was not able to get the information to work in the system. 

Thanks for being willing to help on this though. 

Kind Regards, 

Brett Whittacre 
Vice President 
whit@ec2software.com 
ec 2 Software Solutions 
3035 E. Patrick 
Ste. 1 
Las Vegas, Nevada, 89120 
P : 1.866.791.3673 ext 200 | F: 1.702.947.7357 
www.ec2software.com 
Follow the rules. Exceed the standard .
