### ISSUE TITLE
Typo in the rabbitmq.template.xml

### ISSUE THREAD

**Issue by robin-maxxton** [jasonmcintosh/rabbitmq-zabbix#21]
I believe there is a typo in the RabbitMQ template file.
Please do correct me if I'm wrong :sweat_smile:.

Once I imported the template on the Zabbix server it starts to complaining about the fact that:
`{Template App RabbitMQ v3:rabbitmq[queues].last()}<>0`
is not supported.

Hence the fact that the **.last()** part is missing a parameter and the result does not check against **=0**.
I guess the correct expression should be:
`{Template App RabbitMQ v3:rabbitmq[queues].last(0)}=0`

I traced the problem back to the XML file which describes an incorrect trigger expression [at line 1181](https://github.com/jasonmcintosh/rabbitmq-zabbix/blob/master/rabbitmq.template.xml#L1181).
The problem may have been caused by an earlier merge of the XML file as stated in the commit logs.
Fixing this problem could safe people, who use this template, some time (and zabbix trigger complaints) :smile:.

Lastly I'd like to thank you for this great collection of templates and scripts to support Zabbix logging for the RabbitMQ broker.
It works like a charm without having to spent a huge amount of time on it.

**Comment by jasonmcintosh** [comment]
Fixed in the latest commit :)  Thanks for the catch and let me know if it fixes your import!

**Comment by robin-maxxton** [comment]
Great, it fixes the import.

Another thing I wanted to ask is the purpose of the trigger as described above.
Currently it keeps throwing the trigger event as the 'RabbitMQ Refresh Rabbit Queue Status' item is constantly 1, where the trigger wants it to be everything else than 0 (so it triggers on the value of 1).
Please do correct me if I'm wrong.

While looking into the python code of api.py I notice an odd thing for the check_queue function which gets called for the key **rabbitmq[queues]**. If you have no filters defined in the .rab.auth file then the rdatafile, which should be filled and prepared, stays empty. I believe this causes the _send_data function to always return status code 1, as there's a problem for the collected rdatafile. So normally this should return a status code of 0.

Did I forget to define something for the python scripts or is this problem completely related to the RabbitMQ broker's settings?

**Comment by jasonmcintosh** [comment]
Hrmm, on my side, the queue status is always 0 on my side.  I'll do some testing without a filter set, but I THOUGHT I had a default on it if none was found.  In which case it would report on all queues.

**Comment by jasonmcintosh** [comment]
OH and the purpose of the trigger is to catch a situation where the refresh of queue data fails.  the rabbitmq[queues] check is what then triggers the "zabbix_sender" to send all it's data back.  I could just have as easily used a cron job, but I figured the active check let you have more control via zabbix on refresh rates and such.

**Comment by robin-maxxton** [comment]
Thanks fort the explaination. I'll try to fix it on my side as well. If I can get it to work I'll let you know.

**Comment by robin-maxxton** [comment]
If I lower the logger level to debug and look at my .log file I get a warning from the zabbix_sender:
**WARNING: zabbix_sender [20861]: DEBUG: answer [{"response":"success","info":"processed: 0; failed: 60; total: 60; seconds spent: 0.000662"}]**
So I guess this has maybe something to do with the settings.

**Comment by jasonmcintosh** [comment]
OK so turns out others have had issues with the filter in the template file.  I've got a "corrected" version that worked on my 2.2 installation that I'll get updated here in a while that removes the filter.  I was going to try and get the filter going, but you might try removing the filter from the discovery rule and seeing if that fixes your issues.

**Comment by robin-maxxton** [comment]
You've been a great help. Removing the filter for the discovery rule from my template file does seem to fix the issue. But does this mean that the filter option is completely gone or can it still be used?

**Comment by jasonmcintosh** [comment]
OK finally figured out the issue with the filter.  The filter if you want to use it requires a global regular expression:
https://www.zabbix.com/documentation/2.2/manual/regular_expressions

SO the existing template, if you imported it, wouldn't work without that filter being set.  "rabbitmq vhosts for discovery" would need to get defined and THEN filters on LLD would work.

**Comment by robin-maxxton** [comment]
Good to hear. So that would mean if I'd add the regular expression manually it should work correctly. I guess you will update the repository asap?

**Comment by jasonmcintosh** [comment]
I updated the documentation with the configuration details on how to do this :)  Let me know if you need more details or see other changes to the docs that would help.

But yes apparently if you'd created global regular expression named "rabbitmq vhosts for discovery" LLD of your queues would have worked.  I'd not seen global regular expressions before this so I learned something new!  Also, apparently with 2.4 you can do multiple expressions.  
http://blog.zabbix.com/zabbix-2-4-features-part-1-multiple-lld-filters/3268/

**Comment by jasonmcintosh** [comment]
Note, that I need to test with the filters - I've NOT done much investigation at this point, so the issue of the trigger happening on the 'rabbitmq[queues]' might still be there....

**Comment by robin-maxxton** [comment]
Oke, no problem. I'm glad you helped out this far. I'll be trying some stuff myself in order to better understand the functionality of the template and script. If I run into any other problems I'll let you know.
