### ISSUE TITLE
Cannot import template

### ISSUE THREAD

**Issue by kraison** [jasonmcintosh/rabbitmq-zabbix#23]
I get errors when trying to import the template into Zabbix 2.2.7:

mb_strlen() expects parameter 1 to be string, array given [conf.import.php:130 → CConfigurationImport->import() → CConfigurationImport->processDiscoveryRules() → CAPIObject->create() → CAPIObject->__call() → czbxrpc::call() → czbxrpc::callAPI() → call_user_func() → CDiscoveryRule->create() → CDiscoveryRule->createReal() → DB::insert() → DB::checkValueTypes() → zbx_strlen() → mb_strlen() in /usr/share/zabbix/include/func.inc.php:955]
    pg_escape_string() expects parameter 1 to be string, array given [conf.import.php:130 → CConfigurationImport->import() → CConfigurationImport->processDiscoveryRules() → CAPIObject->create() → CAPIObject->__call() → czbxrpc::call() → czbxrpc::callAPI() → call_user_func() → CDiscoveryRule->create() → CDiscoveryRule->createReal() → DB::insert() → DB::checkValueTypes() → zbx_dbstr() → pg_escape_string() in /usr/share/zabbix/include/db.inc.php:1242]
    Array to string conversion [conf.import.php:130 → CConfigurationImport->import() → CConfigurationImport->processDiscoveryRules() → CAPIObject->create() → CAPIObject->__call() → czbxrpc::call() → czbxrpc::callAPI() → call_user_func() → CDiscoveryRule->create() → CDiscoveryRule->createReal() → DB::insert() → implode() in /usr/share/zabbix/include/classes/db/DB.php:450]
    pg_query(): Query failed: ERROR:  syntax error at or near ","
    LINE 1: ...0','0','','0','','','','','0','','','','','',Array,'1','','r...
                                                                 ^ [conf.import.php:130 → CConfigurationImport->import() → CConfigurationImport->processDiscoveryRules() → CAPIObject->create() → CAPIObject->__call() → czbxrpc::call() → czbxrpc::callAPI() → call_user_func() → CDiscoveryRule->create() → CDiscoveryRule->createReal() → DB::insert() → DBexecute() → pg_query() in /usr/share/zabbix/include/db.inc.php:509]
    Error in query [INSERT INTO items (name,type,snmp_community,snmp_oid,delay,status,snmpv3_contextname,snmpv3_securityname,snmpv3_securitylevel,snmpv3_authprotocol,snmpv3_authpassphrase,snmpv3_privprotocol,snmpv3_privpassphrase,delay_flex,params,ipmi_sensor,authtype,username,password,publickey,privatekey,port,filter,lifetime,description,key_,trapper_hosts,hostid,flags,value_type,data_type,interfaceid,itemid) VALUES ('rabbitmq queues','7','','','360','0','','','0','0','','0','','','','','0','','','','','',Array,'1','','rabbitmq.discovery_queue','','10130','1','4','0',NULL,'24967')] [ERROR:  syntax error at or near ","
    LINE 1: ...0','0','','0','','','','','0','','','','','',Array,'1','','r...
                                                                 ^]
    SQL statement execution has failed "INSERT INTO items (name,type,snmp_community,snmp_oid,delay,status,snmpv3_contextname,snmpv3_securityname,snmpv3_securitylevel,snmpv3_authprotocol,snmpv3_authpassphrase,snmpv3_privprotocol,snmpv3_privpassphrase,delay_flex,params,ipmi_sensor,authtype,username,password,publickey,privatekey,port,filter,lifetime,description,key_,trapper_hosts,hostid,flags,value_type,data_type,interfaceid,itemid) VALUES ('rabbitmq queues','7','','','360','0','','','0','0','','0','','','','','0','','','','','',Array,'1','','rabbitmq.discovery_queue','','10130','1','4','0',NULL,'24967')".

**Comment by msilbermanNTGR** [comment]
This issue is a Zabbix Version issue. The head revision works for 2.4.3, but not for 2.2.3 in my environment. Can a template for 2.2.X be provided or the steps necessary to replicate the bug fixes/changes made to bring the older templates up to date?

**Comment by jasonmcintosh** [comment]
Ok sorry for the delay in responses here - I need to see if I can get a 2.2 setup to test this.  Sorry for the delay on answering.  I THOUGHT I'd had this tested with 2.2 but I'll try and take a look this week to see if I can isolate the issue.

**Comment by ykmaloo** [comment]
I am facing the similar issue with my Zabbix 2.2.9 version. Maybe what needed is a template which works with Zabbix 2.2.x version.

**Comment by msilbermanNTGR** [comment]
I believe Jason is working on getting a template for 2.2.x, but in the mean time I pulled the template from the 2.0.1 tag and it is importable and works on 2.2.3 without any changes.
Jason: Thank you for your help and the code! Made my life a little easier.

**Comment by ykmaloo** [comment]
Could please let me know the location for the template from 2.0.1 tag or upload it here. SO that in the meantime i can work on that.

Thanks in advance.

**Comment by jasonmcintosh** [comment]
Sorry all I've been swamped - working on the farm and my day job has also been crazy.  
https://github.com/jasonmcintosh/rabbitmq-zabbix/tree/v2.0.1
Should get you going.  I'll try and get more work on this done this weekend when I get some spare time.

**Comment by mailo84** [comment]
Don't work on zbx 2.2.5 , can't import tmplate

**Comment by hoffmannliu-ayla** [comment]
The modified template works at least for 2.2.6. Thanks!!
