### ISSUE TITLE
WARNING: zabbix_sender Warning: 'Server' parameter required

### ISSUE THREAD

**Issue by darksmoke** [jasonmcintosh/rabbitmq-zabbix#24]
good afternoon

Do not send data
He writes in the logfile rabbitmq_zabbix.log

2015-07-01 13:01:56,208 WARNING: Sending failed.
2015-07-01 13:01:56,209 WARNING: zabbix_sender [937004]: Warning: 'Server' parameter required

**Comment by jasonmcintosh** [comment]
This is a configuration on your client side.  It appears your zabbix agent isn't installed in a standard location or configuration.  You CAN as an option specify a zabbix server by modifying the scripts to add either "--senderhostname" to the call to api.py, OR set a CONF variable in the .rab.auth that points to your zabbix config file.

**Comment by darksmoke** [comment]
cat .rab.auth 
USERNAME=admin
PASSWORD=pass
CONF=/opt/zabbix/etc/zabbix_agent.conf


Rules such lines
api.py

Line 15
logging.basicConfig(filename='/opt/zabbix/log/rabbitmq_zabbix.log', level=logging.WARNING, format='%(asctime)s %(levelname)s: %(message)s')

Line 20
def __init__(self, user_name='guest', password='guest', host_name='', port=15672, conf='/opt/zabbix/etc/zabbix_agentd.conf', senderhostname=None):

Line 89
args = '/opt/zabbix/bin/zabbix_sender -c {0} -i {1} -vv'

The error does not go away

**Comment by darksmoke** [comment]
The problem with zabbix_sender I understand

**Comment by darksmoke** [comment]
Fixed zabbix_agent.conf on zabbix_agentd.conf
Zabbix sender started to send, but successful 0

2015-07-02 17:05:13,088 WARNING: info from server: "processed: 0; failed: 12; total: 12; seconds spent: 0.000111"
sent: 12; skipped: 0; total: 12

2015-07-02 17:05:13,088 WARNING: zabbix_sender [1023679]: DEBUG: answer [{"response":"success","info":"processed: 0; failed: 12; total: 12; seconds spent: 0.000111"}]

2015-07-02 17:05:43,235 WARNING: info from server: "processed: 0; failed: 12; total: 12; seconds spent: 0.000176"
sent: 12; skipped: 0; total: 12

2015-07-02 17:05:43,235 WARNING: zabbix_sender [1023697]: DEBUG: answer [{"response":"success","info":"processed: 0; failed: 12; total: 12; seconds spent: 0.000176"}]

**Comment by darksmoke** [comment]
Help me

**Comment by jasonmcintosh** [comment]
Off hand, it appears that it found queues to send data on, but the server didn't have any items discovered.  Check the auto discovery rule on your host to make sure it actually created the entries.  If you got to a specific host, look at the items on that host, make sure your entries show up.  Also, check that the auto discovery rule hasn't had any errors.  Last, you can verify that the keys being sent back match what the server discovered.  The recent api.py calls changed the entries slightly to be rabbit.queues vs rabbit[*]

**Comment by jasonmcintosh** [comment]
Closing this - not heard anything in a while.
