### ISSUE TITLE
zabbix_sender, code return

### ISSUE THREAD

**Issue by RussianFox** [jasonmcintosh/rabbitmq-zabbix#26]
Template App RabbitMQ v3:rabbitmq[queues].last(0)}#0

I suggest replacing
Template App RabbitMQ v3:rabbitmq[queues].last(0)}=1
because exit code 2 is not error in zabbix_sender
https://www.zabbix.com/documentation/2.4/manpages/zabbix_sender

Exit code of zabbix_sender =2 with filter in Discovery, because api.py sending data for all hosts

**Comment by jasonmcintosh** [comment]
Will look into and get it fixed, thanks for the report!

**Comment by jasonmcintosh** [comment]
Note, what I may do is have a warning level trigger on 2 and higher level trigger on return code 1.

**Comment by jasonmcintosh** [comment]
SO one thing did is removed the filter entirely.  Was causing too many people too many headaches (me included).  I'll do testing see if that fixes the sender, but regardless, should change it to do #0 :)

**Comment by jasonmcintosh** [comment]
Should be fixed now in the latest release!
