### ISSUE TITLE
fix node in config

### ISSUE THREAD

**Issue by ivan1986** [jasonmcintosh/rabbitmq-zabbix#28]
````
TYPE_OF_CHECK=$1
METRIC=$2

if [[ $3 ]]; then
    NODE=$3
fi
if [[ -z "$HOSTNAME" ]]; then
    HOSTNAME=`hostname`
fi
````

**Comment by jasonmcintosh** [comment]
Hrmm, the only problem I see with this is if $3 ISN'T passed, NODE is never set.  It's why I default NODE to HOSTNAME.  Is there a specific problem here you're hitting?

**Comment by ivan1986** [comment]
if zabbix agent not in rabbit server can not set default node for server monitoring
i see cluster partition warning in my case, but it's on coreos in container

**Comment by jasonmcintosh** [comment]
I need to look at adding logic so that it tries to find the node if it's blank kinda thing.  Appreciate the bug report - just got to find time to verify and figure out the right fix.

**Comment by jasonmcintosh** [comment]
Should be fixed - I basically changed this to say if there is only a single node, ignore trying to find the matching node and just use that.
