### ISSUE TITLE
Zabbix 2.2 Monitoring RabbitMQ

### ISSUE THREAD

**Issue by almaza** [jasonmcintosh/rabbitmq-zabbix#29]
Hi,

Could not find this detailed anywhere so I thought I should mention it for those who are still using an older Zabbix version.

The latest Template version do not work without editing so to make it easier for myself I used the archived 2.0.0 version of the template. This installed perfectly and everything worked except the discovered queues did not return any data.

tail -f /var/log/zabbix/rabbitmq_zabbix.log kept showing failed items
WARNING: info from server: "processed: 0; failed: 42; total: 42; seconds spent: 0.000486"

After setting the api.py to DEBUG instead of WARNING it showed me the key's sent to the zabbix_sender and I could replicate the problem manually and noticed the key in Zabbix and the key returned by the api were not the same.

This was resolved by adding .queues to the 6 x Template -> Discovery Rules -> Item Prototype -> Key
Example:
From
rabbitmq[{#VHOSTNAME},queue_message_stats_deliver_get,{#QUEUENAME}]
To
rabbitmq.queues[{#VHOSTNAME},queue_message_stats_deliver_get,{#QUEUENAME}]

Hope this helps someone :)
Alm

**Comment by jasonmcintosh** [comment]
*SIGH* I need to spend some time cleaning this stuff up and testing on both 2.2. and 2.4 releases of zabbix.  My apologies on this!

**Comment by jasonmcintosh** [comment]
This should be fixed - closing out old issue and if there's a problem still can reopen or open a new ticket.
