### ISSUE TITLE
Zabbix agent (active) insted of Zabbix agent

### ISSUE THREAD

**Issue by mwisniewski87** [jasonmcintosh/rabbitmq-zabbix#30]
Template contains items of type - Zabbix agent (active) - except of aliveness test which is just Zabbix Agent. I do not get values for them as long as they are 'active'. 

After mass change to pure Zabbix agent type they give values back.

Is this a real issue, or I've made a mistake at the other point of configuration?

**Comment by jasonmcintosh** [comment]
At a guess, check to make sure your agent is setup with active checks enabled.  We HAVE had issues where either that hasn't been set OR there are timeouts on the checks.  If the active check takes too long it'll kill the check.  Log files should help with this.

I generally tend to run more passive checks personally, but I leave active as the default for certain environments that have issues with firewalls.
