### ISSUE TITLE
How can i monitor a queue length?

### ISSUE THREAD

**Issue by itJunky** [jasonmcintosh/rabbitmq-zabbix#34]
In default userparameters of this template i don't see a item or similar userparam for getting queue messages count. I need a trigger for more than 2000 messages in all queues.

How can i do this with your module?

**Comment by itJunky** [comment]
Temporary i set this userparameter:
UserParameter=rabbitmaxq,sudo rabbitmqctl list_queues | grep -vE "Listing queues|.done." | awk '{s+=$2} END {print s}'

But it realy need to support by this module "from the box"

**Comment by jasonmcintosh** [comment]
Be very very careful on using rabbitmqctl to monitor rabbit - it's a fairly heavyweight process.  That's one reason I wrote the API's that I did.  Look at (with the latest template) auto-discovered items.  Each queue is discovered, and some basic triggers are setup.  You can tweak that there.  If you want OVERALL server rates and a trigger on that, you can add a server item to get that value.  I don't have the API in front of me, but it should be something like rabbitmq.server[messages] or similar.

**Comment by itJunky** [comment]
Before i write this issue, i check discovery scripts and get from it only names of queus, but i need a length of each queue(now i summarize all lengths and send to zabbix)
