### ISSUE TITLE
Can't get queues to work

### ISSUE THREAD

**Issue by adamlc** [jasonmcintosh/rabbitmq-zabbix#36]
Hey guys, thanks for writing this plugin!

I'm having a few issues, been pulling my hair out all afternoon over this. For some reason the queues don't seem to be working. I've created a filter, which seems to be working according to the logs:

```
2016-02-16 16:25:30,983 DEBUG: SENDER_DATA: - "rabbitmq.queues[/,queue_memory,jumplead.illuminate_task]" 17512
2016-02-16 16:25:30,983 DEBUG: SENDER_DATA: - "rabbitmq.queues[/,queue_messages,jumplead.illuminate_task]" 0
2016-02-16 16:25:30,983 DEBUG: SENDER_DATA: - "rabbitmq.queues[/,queue_messages_unacknowledged,jumplead.illuminate_task]" 0
2016-02-16 16:25:30,983 DEBUG: SENDER_DATA: - "rabbitmq.queues[/,queue_consumers,jumplead.illuminate_task]" 0
2016-02-16 16:25:30,983 DEBUG: SENDER_DATA: - "rabbitmq.queues[/,queue_message_stats_deliver_get,jumplead.illuminate_task]" 4383
2016-02-16 16:25:30,983 DEBUG: SENDER_DATA: - "rabbitmq.queues[/,queue_message_stats_publish,jumplead.illuminate_task]" 4332
```

But unfortunately zabbix_sender seems to be rejecting them:
```
2016-02-16 16:25:31,003 WARNING: info from server: "processed: 0; failed: 6; total: 6; seconds spent: 0.000129"
sent: 6; skipped: 0; total: 6
```

Any idea whats wrong? I'm not sure if I've setup the Regular expressions correctly. I've created a regexp called ```rabbitmq vhosts for discovery``` with this exp ```^/$``` with result is true (I've tried a few combinations. Am I missing anything?

Also some of the server checks are failing, for example ```RabbitMQ Server Partitions``` is currently ```Not Found```, but I'm not sure if this is due to the queues part failing?

Thanks guys!

**Comment by adamlc** [comment]
Forgot to mention, I'm using Zabbix 3.0 and RabbitMQ 3.6.0 if that makes any difference :+1:

**Comment by DenisBY** [comment]
I have same problem

**Comment by aazheglov** [comment]
I had the same problem.
Zabbix-server didn't receieve data from zabbix_sender:
`info from server: "processed: 0; failed: 12; total: 12; seconds spent: 0.000367"`

I tried to send data with zabbix_sender manualy in the same way as api.py does:
```
def _send_data(self, tmpfile):
        '''Send the queue data to Zabbix.'''
        args = 'zabbix_sender -c {0} -i {1}'
        if self.senderhostname:
            args = args + " -s " + self.senderhostname
```
`# zabbix_sender -c /etc/zabbix/zabbix_agentd.conf -s @hostname@ -k @key@ -o @value@`
And data was sent...
`info from server: "processed: 1; failed: 0; total: 1; seconds spent: 0.000050"`

But for `senderhostname` api.py can use hostname from zabbix_agentd.conf or server hostname:
`self.senderhostname = senderhostname if senderhostname else host_name`

I saw, that host name on zabbix-server and server hostname were different. I don't know, why api.py doesn't take `senderhostname` from `zabbix_agentd.conf`, but after I changed host name on zabbix-server, it started receieving data:
`info from server: "processed: 12; failed: 0; total: 12; seconds spent: 0.000286"`

PS. sorry, my English isn't very good... :)

PPS. if in some reason you have 2 IPs in "server" option in zabbix_agentd.conf zabbix_sender will use only first.

**Comment by adamlc** [comment]
Thanks for the heads up @aazheglov, that fixed one of the issues I was having! Turns out that the discovery was broken because list_rabbit_nodes.sh and list_rabbit_queues.sh weren't passing my custom HOSTNAME and NODE values across. Because zabbix couldn't discover the extra variables it broke. I've created a PR #38 that fixes the issue :smile:

**Comment by jasonmcintosh** [comment]
I apologize for the delay on responding on all of this - I've not had near enough time lately with a new role at work to be able to spend as I'd like improving and fixing bugs on this.  Thank you VERY much for the PR and fix!!!
