### ISSUE TITLE
Problem with item "RabbitMQ Check Aliveness"

### ISSUE THREAD

**Issue by aazheglov** [jasonmcintosh/rabbitmq-zabbix#37]
Hi, thanks for this plugin - it saves a lot of my time. :)

All works fine, except item "RabbitMQ Check Aliveness"...
In some reason zabbix-agent returns traceback:
```
Traceback (most recent call last):
  File "./api.py", line 212, in <module>
    main()
  File "./api.py", line 201, in main
    print api.check_aliveness()
  File "./api.py", line 138, in check_aliveness
    return self.call_api('aliveness-test/%2f')['status']
  File "./api.py", line 37, in call_api
    return json.loads(urllib2.build_opener(handler).open(url).read())
  File "/usr/lib/python2.7/urllib2.py", line 406, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 519, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 438, in error
    result = self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 378, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 890, in http_error_401
    url, req, headers)
  File "/usr/lib/python2.7/urllib2.py", line 865, in http_error_auth_reqed
    response = self.retry_http_basic_auth(host, req, realm)
  File "/usr/lib/python2.7/urllib2.py", line 878, in retry_http_basic_auth
    return self.parent.open(req, timeout=req.timeout)
  File "/usr/lib/python2.7/urllib2.py", line 406, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 519, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 444, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 378, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 527, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 401: Unauthorized
```

PS. I created `.rab.auth` with `USERNAME` and `PASSWORD` where set login and password of rabbitmq user.

**Comment by jasonmcintosh** [comment]
The aliveness test it issues is getting a denied - likely the user being used doesn't have config permissions on the default queue.  The aliveness test creates a queue, publishes and consumes a message from that queue.  More information is available here:

http://hg.rabbitmq.com/rabbitmq-management/raw-file/rabbitmq_v2_2_0/priv/www-api/help.html

SO check that the user you're specifying has full permissions.  You can test it yourself by going to:

http://hostname:15672/api/aliveness-test/vhost

Where vhost should be (as I recall off top of my head) %2F URL Encoded.

**Comment by mschedrin** [comment]
For those looking for quick answer:
`rabbitmqctl add_user zabbix pass
rabbitmqctl set_user_tags zabbix management
rabbitmqctl set_permissions -p / zabbix '^aliveness-test$' '^amq\.default$' '^aliveness-test$'
`
Probably worth adding to documentation.

**Comment by jasonmcintosh** [comment]
Updated readme file with the commands.

**Comment by mschedrin** [comment]
Actually, the user tag should be 'monitoring', not 'management'. I've corrected my message.

**Comment by dashap** [comment]
Question on vhost.  To use ldap I have for example in ldap:

cn=test-users,ou=groups,dc=company,dc=com, where in this case vhost is test.  It fails authentication if I make my vhost /test instead of just test, so it was created with rabbitmqctl add_vhost test instead of rabbitmqctl add_vhost /test.

Do I need to change the AD to be cn=/test-users,ou=groups,dc=company,dc=com?  Do we need vhosts to have the forward slash?  If not, what would be the curl call to https://localhost:15672 to do a check on vhost test?

**Comment by insideClaw** [comment]
Can confirm @mschedrin's solution works. Here's the code phrased in Ansible:
```
  - name: create RabbitMQ user authorized to monitor
    rabbitmq_user:
      name: "someuser"
      password: "somepass"
      permissions:
        - vhost: /
          configure_priv: ^aliveness-test$
          write_priv: ^amq\.default$
          read_priv: ^aliveness-test$
        - vhost: "{{item.name}}"
          configure_priv: .*
          write_priv: .*
          read_priv: .*
      state: present
      tags: management
    with_items: "{{user_system_users}}"
    when: web_install_rabbitmq
    tags: rabbitmq
```
It includes some configuration-specific permissions for vhosts.
