### ISSUE TITLE
Unable to see anything in Zabbix

### ISSUE THREAD

**Issue by PritiRanjanSahoo** [jasonmcintosh/rabbitmq-zabbix#39]
I have downloaded and installed the plugin into /etc/zabbix/scripts/rabbit folder. I have also created a .rab.auth file there in the same folder. ~/.rabbitmq-status.sh list_queues also gives me result as expected from a remote machine.

However I am not able to see anything in Zabbix for any of the 16 Templates. All I could see some tweaks was a 400 Bad Request. Do you have any pointers on how to troubleshoot this issue? Am I missing anything in the Templates that is causing this? If you have a more detailed guide on configuring the Templates that will also be helpful. I am presently trying to `check-aliveness` work.

Here is the /var/log/zabbix/zabbix-server.log
```
24616:20160516:174458.893` error reason for "192.168.5.222:vfs.fs.size[D:,used]" changed: Received value [HTTP/1.1 400 Bad RequestServer: MochiWeb/1.0 (Any of you quaids got a smint?)Date: Mon, 16 May 2016 12:14:59 GMTContent-Length: ] is not suitable for value type [Numeric (unsigned)] and data type [Decimal]
````

**Comment by jasonmcintosh** [comment]
SO if you can import the template into zabbix, you should see the templates.  There IS a global regular expression on them that has to be created btw.

**Comment by jasonmcintosh** [comment]
Closing this as not heard anything in a while and this does not look like an issue with the rabbitmq stuff.
