### ISSUE TITLE
rabbitmq.queues Unsupported item key.

### ISSUE THREAD

**Issue by Klef** [jasonmcintosh/rabbitmq-zabbix#40]
Good day.
Not found item rabbitmq.queues in zabbix-rabbitmq.conf

**Comment by Klef** [comment]
sorry, miss

**Comment by gilbsgilbs** [comment]
Hi! How did you solve this? Thanks!

**Comment by jasonmcintosh** [comment]
rabbitmq.queues entries are designed to be trap items.  Meaning that they're generated as part of the discovery rule, and then the client PUSHES those values back to the server vs. being in a confi file.  If you've change things to be something other than a trap, you'll have to change a number of things to get things to work.

**Comment by gilbsgilbs** [comment]
Hi @jasonmcintosh. Thanks for this precise answer. I'm new to Zabbix, so I'm not sure I got everything, but  as of now, this project does not provide any way to create per-queue items/triggers, am I right?

Yet I had the same issue with `rabbitmq.discovery_nodes`. Is it a trap item also ? How Zabbix server is supposed to be configured to display alerts and such things?
