### ISSUE TITLE
Enable SSL 

### ISSUE THREAD

**Issue by emccormickva** [jasonmcintosh/rabbitmq-zabbix#59]
Hello,

I use SSL exclusively for my rabbitmq setup. Would it be possible to have an option to use SSL to perform API functions?

Thanks,
Erik

P.S. I've temporarily enabled HTTP for the admin to get around this and set it to listen on other interfaces to get around the other and it works fine that way. I would just like to be able to use it as I had it. Thanks for a great plugin and all your hard work!

**Comment by jasonmcintosh** [comment]
Someone someplace I THOUGHT had added support for SSL in a fork (I've not bothered yet).  Feel free to fork and contribute.  It shouldn't be too hard to add SSL support - likely a "--protocol" http default, "https" and a "--port" option as well, then updates to the api.py to support the options.  The harder part might be things like adding all the SSL parameters (e.g. cert files, etc.)

**Comment by emccormickva** [comment]
I haven't come across the fork yet, and you're still paying attention to this so I certainly wouldn't want to fork it. I'll see what I can put together to make SSL work and send in a pull request when I get there.

**Comment by jasonmcintosh** [comment]
https://github.com/jasonmcintosh/rabbitmq-zabbix/tree/https_support

Give that branch a try.  Just update the .rab.auth file to set PROTOCOL and PORT appropriately.  Note, I've NOT added parameters for CA or other config options yet...

**Comment by jasonmcintosh** [comment]
https://github.com/jasonmcintosh/rabbitmq-zabbix/pull/64

**Comment by jasonmcintosh** [comment]
Closing this as support is now in mainline branch.
