### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by espala** [jasonmcintosh/rabbitmq-zabbix#60]
Hello,

Can you help me ?

![screen shot 2016-12-15 at 09 31 52](https://cloud.githubusercontent.com/assets/9979648/21214414/4b3043b6-c2a3-11e6-8709-a7c237bb646c.png)
![screen shot 2016-12-15 at 08 42 00](https://cloud.githubusercontent.com/assets/9979648/21214417/4ebd2e0e-c2a3-11e6-9583-bc888fd10293.png)

Error Messages is;
RabbitMQ Message Deliver Rates
 RabbitMQ Message Receive Rates
Received value [Traceback (most recent call last): File "./api.py", line 277, in <module> main() File "./api.py", line 272, in main print api.check_server(options.metric, options.node) File "./api.py", line 199, in check_server return self.call_api('overview').get('message_stats', {}).get('deliver_get_details', {}).get('rate',0) File "./api.py", line 35, in call_api return json.loads(urllib2.build_opener(handler).open(url).read()) File "/usr/lib64/python2.6/urllib2.py", line 397, in open response = meth(req, response) File "/usr/lib64/python2.6/urllib2.py", line 510, in http_response 'http', request, response, code, msg, hdrs) File "/usr/lib64/python2.6/urllib2.py", line 429, in error result = self._call_chain(*args) File "/usr/lib64/python2.6/urllib2.py", line 369, in _call_chain result = func(*args) File "/usr/lib64/python2.6/urllib2.py", line 880, in http_error_401 url, req, headers) File "/usr/lib64/python2.6/urllib2.py", line 858, in http_error_auth_reqed return self.retry_http_basic_auth(host, req, realm) File "/usr/lib64/python2.6/urllib2.py", line 868, in retry_http_basic_auth return self.parent.open(req, timeout=req.timeout) File "/usr/lib64/python2.6/urllib2.py", line 397, in open response = meth(req, response) File "/usr/lib64/python2.6/urllib2.py", line 510, in http_response 'http', request, response, code, msg, hdrs) File "/usr/lib64/python2.6/urllib2.py", line 435, in error return self._call_chain(*args) File "/usr/lib64/python2.6/urllib2.py", line 369, in _call_chain result = func(*args) File "/usr/lib64/python2.6/urllib2.py", line 518, in http_error_default raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)urllib2.HTTPError: HTTP Error 401: Unauthorized] is not suitable for value type [Numeric (float)]

RabbitMQ Refresh Rabbit Queue Status
RabbitMQ Server Memory Used
Received value [Traceback (most recent call last): File "./api.py", line 277, in <module> main() File "./api.py", line 262, in main print api.check_queue(filters) File "./api.py", line 106, in check_queue for queue in self.call_api('queues'): File "./api.py", line 35, in call_api return json.loads(urllib2.build_opener(handler).open(url).read()) File "/usr/lib64/python2.6/urllib2.py", line 397, in open response = meth(req, response) File "/usr/lib64/python2.6/urllib2.py", line 510, in http_response 'http', request, response, code, msg, hdrs) File "/usr/lib64/python2.6/urllib2.py", line 429, in error result = self._call_chain(*args) File "/usr/lib64/python2.6/urllib2.py", line 369, in _call_chain result = func(*args) File "/usr/lib64/python2.6/urllib2.py", line 880, in http_error_401 url, req, headers) File "/usr/lib64/python2.6/urllib2.py", line 858, in http_error_auth_reqed return self.retry_http_basic_auth(host, req, realm) File "/usr/lib64/python2.6/urllib2.py", line 868, in retry_http_basic_auth return self.parent.open(req, timeout=req.timeout) File "/usr/lib64/python2.6/urllib2.py", line 397, in open response = meth(req, response) File "/usr/lib64/python2.6/urllib2.py", line 510, in http_response 'http', request, response, code, msg, hdrs) File "/usr/lib64/python2.6/urllib2.py", line 435, in error return self._call_chain(*args) File "/usr/lib64/python2.6/urllib2.py", line 369, in _call_chain result = func(*args) File "/usr/lib64/python2.6/urllib2.py", line 518, in http_error_default raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)urllib2.HTTPError: HTTP Error 401: Unauthorized] is not suitable for value type [Numeric (unsigned)] and data type [Decimal]

RabbitMQ Refresh Rabbit Shovel Status
RabbitMQ Server File Desc Used
RabbitMQ Server Sockets Used
Received value [Traceback (most recent call last): File "./api.py", line 277, in <module> main() File "./api.py", line 264, in main print api.check_shovel(filters) File "./api.py", line 131, in check_shovel for shovel in self.call_api('shovels'): File "./api.py", line 35, in call_api return json.loads(urllib2.build_opener(handler).open(url).read()) File "/usr/lib64/python2.6/urllib2.py", line 397, in open response = meth(req, response) File "/usr/lib64/python2.6/urllib2.py", line 510, in http_response 'http', request, response, code, msg, hdrs) File "/usr/lib64/python2.6/urllib2.py", line 435, in error return self._call_chain(*args) File "/usr/lib64/python2.6/urllib2.py", line 369, in _call_chain result = func(*args) File "/usr/lib64/python2.6/urllib2.py", line 518, in http_error_default raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)urllib2.HTTPError: HTTP Error 404: Object Not Found] is not suitable for value type [Numeric (unsigned)] and data type [Decimal]

RabbitMQ Server File Desc Percent Used
RabbitMQ Server Memory Percent Used
RabbitMQ Server Sockets Percent Used
Cannot evaluate expression: "Cannot evaluate function "last()".".

I just did the following.

[root@rabbitmqtest01 /etc/zabbix]$python -V
Python 2.6.6

[root@rabbitmqtest01 /etc/zabbix]$rabbitmqadmin --version
rabbitmqadmin 3.6.5

[root@rabbitmqtest01 /etc/zabbix]$yum list installed |grep zabbix
zabbix-agent.x86_64              3.2.2-1.el6                @zabbix
zabbix-release.noarch            3.2-1.el6                  @zabbix
zabbix-sender.x86_64             3.2.2-1.el6                @zabbix

[root@rabbitmqtest01 /etc/zabbix]$pwd
/etc/zabbix

[root@rabbitmqtest01 /etc/zabbix]$ls
scripts  zabbix_agentd.conf  zabbix_agentd.d

[root@rabbitmqtest01 /etc/zabbix]$cat zabbix_agentd.conf
PidFile=/var/run/zabbix/zabbix_agentd.pid
LogFile=/var/log/zabbix/zabbix_agentd.log
LogFileSize=5
DebugLevel=3
EnableRemoteCommands=1
LogRemoteCommands=1
HostMetadataItem=system.uname
Hostname=rabbitmqtest01
Server=127.0.0.1,zabbixmaster
ServerActive=zabbixmaster
Include=/etc/zabbix/zabbix_agentd.d/

[root@rabbitmqtest01 /etc/zabbix]$cat zabbix_agentd.d/userparameter_rabbitmq.conf
UserParameter=rabbitmq.discovery_queues,/etc/zabbix/scripts/list_rabbit_queues.sh
UserParameter=rabbitmq.discovery_shovels,/etc/zabbix/scripts/list_rabbit_shovels.sh
UserParameter=rabbitmq.discovery_nodes,/etc/zabbix/scripts/list_rabbit_nodes.sh
UserParameter=rabbitmq[*],/etc/zabbix/scripts/rabbitmq-status.sh $1 $2 $3

[root@rabbitmqtest01 /etc/zabbix]$ls scripts/
api.py  list_rabbit_nodes.sh  list_rabbit_queues.sh  list_rabbit_shovels.sh  rabbitmq-status.sh

[root@rabbitmqtest01 /etc/zabbix]$cat scripts/.rab.auth
USERNAME=guest
PASSWORD=guest
CONF=/etc/zabbix/zabbix_agent.conf

**Comment by jasonmcintosh** [comment]
" HTTP Error 401: Unauthorized] " the user you're using doesn't have access, etc.  Fix the permissions.
