### ISSUE TITLE
Authentication using guest user

### ISSUE THREAD

**Issue by trevorrea** [jasonmcintosh/rabbitmq-zabbix#62]
Hi Jason,

First of all thanks for creating this - it's very useful. 

Not sure this is really an issue but when configuring this today I was getting authentication refused.  I then loudly told a co-worker that guest:guest only works on localhost (i.e. 127.0.0.1) and not any other interface and then spent half an hour like an idiot trying to figure out why I was getting a 401 response. Eventually I gave up and ran tcpdump and immediately saw the problem.

The change to disallow guest access except to localhost was introduced in RabbitMQ 3.3 which was released in 2014 - https://www.rabbitmq.com/blog/2014/04/02/breaking-things-with-rabbitmq-3-3/

So with that said would it make sense for the default hostname to be set to 127.0.0.1 or if not update the readme to reference that if you are using guest:guest and RabbitMQ >= 3.3 then the hostname must be set in .rab.auth as HOSTNAME=127.0.0.1 in order to authenticate correctly.

I'm happy to open an MR but just wanted to get your thoughts before I did so.

Thanks,
Trevor

**Comment by jasonmcintosh** [comment]
From a security perspective, I'd argue you should NEVER use guest:guest for monitoring, but a separate user that's setup with no configuration permissions.  You're right that I should update the documentation to recommend this and warn that if using guest/guest that localhost should be used as it's the only way for that account to work.

SO My thoughts right now are to update the wiki/README with a warning like

### Basic security recommendation (BE AWARE)
 * you should make sure not to use guest which is an admin account
 * setup a read only account who can access the management API.  
 * Make sure that account is READ ONLY
 * IF using guest warning - it can only access RabbitMQ management via localhost so you need to set HOSTNAME=localhost

**Comment by jasonmcintosh** [comment]
Added a note on this - see if you think that fixes your request

**Comment by trevorrea** [comment]
Hi Jason,

That's excellent.  Closing issue.

Regards,
Trevor
