### ISSUE TITLE
HTTP Error 404: Object Not Found

### ISSUE THREAD

**Issue by c10gue** [jasonmcintosh/rabbitmq-zabbix#66]
Hello,

I'm having an issue with trying to get the Rabbit monitoring up and running:

6	
Traceback (most recent call last):
  File "./api.py", line 275, in <module>
    main()
  File "./api.py", line 264, in main
    print api.check_aliveness()
  File "./api.py", line 196, in check_aliveness
    return self.call_api('aliveness-test/%2f')['status']
  File "./api.py", line 36, in call_api
    return json.loads(urllib2.build_opener(handler).open(url).read())
  File "/usr/lib64/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 469, in error
    result = self._call_chain(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 926, in http_error_401
    url, req, headers)
  File "/usr/lib64/python2.7/urllib2.py", line 901, in http_error_auth_reqed
    response = self.retry_http_basic_auth(host, req, realm)
  File "/usr/lib64/python2.7/urllib2.py", line 914, in retry_http_basic_auth
    return self.parent.open(req, timeout=req.timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 404: Object Not Found

Any help would be much appreciated.

Thanks

**Comment by c10gue** [comment]
Just an update to this. I can run the scripts fine via ./list_rabbit_nodes.sh ./list_rabbit_queues.sh ./list_rabbit_shovels.sh

However I seem to get an error on ./rabbitmq-status.sh

api.py: error: option --check: invalid choice: '' (choose from 'list_queues', 'list_shovels', 'list_nodes', 'queues', 'shovels', 'check_aliveness', 'server')

I've check all the permissions and as far as I can see they seem fine. Any ideas?

**Comment by jasonmcintosh** [comment]
Looking at those I'd guess you're missing some of the parameters
e.g. ./rabbitmq-status.sh requires up to 3 parameters.  Part 1 is the type of check, e.g. server, 2 is the metric, and 3 is the node (if needed).  

SO you could do 
```
./rabbitmq-status.sh server message_stats_deliver_get
```

Now, on the first one - it's likely that the api isn't working the way expected.  Normally you can call
https://rawcdn.githack.com/rabbitmq/rabbitmq-management/rabbitmq_v3_6_9/priv/www/api/index.html

http://rabbithost:15672/api/aliveness-test//%2f

IF you can hit that page from your machine, should be fine.  If you can't, I'd question your rabbitmq setup ;)  OR user access ;)  Rabbitmq management plugin IS required for all this stuff to work.

**Comment by c10gue** [comment]
Thanks for this Jason.

I've figured out by our default setup we delete the / vhost hence why it wasn't working.

The status is now showing ok but no data in the rest of the templates field. I've attached a screenshot.
![capture](https://cloud.githubusercontent.com/assets/23035515/25192245/68b1c70e-252a-11e7-95c5-a614e6fc2cc4.PNG)

**Comment by jasonmcintosh** [comment]
Have you checked the host config?  Usually in this case, something is mis-configured.  Note, that the discovery creates the above, then there's a single template item that actually does a remote call to batch send the results back.  

An initial guess MIGHT be hostname differences...  hard to say though without looking at what the error is.  You can also do zabbix_get's from your server side to validate that's working, as well as turn logging on the agent side to verify things.

**Comment by jasonmcintosh** [comment]
OH one other thing... check /api/overview/ - that's where most of the server requests hit to get statistics.  Particularly in the message_stats area.  Only other thought is that there's a permissions issue on the end user side (e.g. zabbix account can't run the scripts?).  You can sudo to the zabbix user try running the scripts by hand:
$check_status.sh server message_stats_publish

**Comment by jasonmcintosh** [comment]
Get this figured out?

**Comment by jasonmcintosh** [comment]
Closing for now, if there are issues re-open

**Comment by agborkowski** [comment]
that error comes from rabbitmq api, i have same problem, i have a node

```
curl http://guest:guest@localhost:15672/api/nodes
<cut...>
["rabbitmq_management"],"name":"prod@prod-1","type":"disc","running":true}]
```
then @newrelic requesting health by url `http://localhost:15672/api/healthchecks/node/prod@prod-1`
new relic daemon response:
```
Response [error] for node [prod@prod-1]: unexpected http response from [http://localhost:15672/api/healthchecks/node/prod@prod-1]: 404 Object Not Found|node:prod@prod-1
```

but the same is for `curl http://guest:guest@localhost:15672/api/healthchecks/node/prod@prod-1`
then:
{"error":"Object Not Found","reason":"\"Not Found\"\n"}

i tried too w/o success
- curl http://guest:guest@localhost:15672/api/healthchecks/node/prod@prod-1
- curl http://guest:guest@localhost:15672/api/healthchecks/node/prod
- curl http://guest:guest@localhost:15672/api/healthchecks/node/prod-1
- curl http://guest:guest@localhost:15672/api/healthchecks/node/prod%40prod-1

**Comment by jasonmcintosh** [comment]
This is likely because your node/cluster is set with a custom name - you can look at the hostname option but until you know that information, going to be hard to assist.  You can curl the API to get more information on available nodes to query - though I don't recall the end point at this time.  If you go to /api/ on the end point, you can see the various API options.
