### ISSUE TITLE
Template error

### ISSUE THREAD

**Issue by kommeht3d** [jasonmcintosh/rabbitmq-zabbix#67]
hello
my zabbix version is 2.4
when I imported the template, I got an error. please, help

mb_strlen() expects parameter 1 to be string, array given [include/func.inc.php:831]
mysql_real_escape_string() expects parameter 1 to be string, array given [include/db.inc.php:646]
Array to string conversion [include/classes/db/DB.php:408]
Error in query [INSERT INTO items (name,type,snmp_community,snmp_oid,delay,status,snmpv3_securityname,snmpv3_securitylevel,snmpv3_authpassphrase,snmpv3_privpassphrase,delay_flex,params,ipmi_sensor,authtype,username,password,publickey,privatekey,port,filter,lifetime,description,key_,trapper_hosts,hostid,flags,value_type,data_type,interfaceid,itemid) VALUES ('rabbitmq queues','7','','','360','0','','0','','','','','','0','','','','','',Array,'1','','rabbitmq.discovery_queues','','10210','1','4','0',NULL,'31802')] [Unknown column 'Array' in 'field list']
SQL statement execution has failed "INSERT INTO items (name,type,snmp_community,snmp_oid,delay,status,snmpv3_securityname,snmpv3_securitylevel,snmpv3_authpassphrase,snmpv3_privpassphrase,delay_flex,params,ipmi_sensor,authtype,username,password,publickey,privatekey,port,filter,lifetime,description,key_,trapper_hosts,hostid,flags,value_type,data_type,interfaceid,itemid) VALUES ('rabbitmq queues','7','','','360','0','','0','','','','','','0','','','','','',Array,'1','','rabbitmq.discovery_queues','','10210','1','4','0',NULL,'31802')".

**Comment by jasonmcintosh** [comment]
The template really requires Zabbix 3.0+ at this point... there's a slightly older version of the template that would work with some tweaking.  
https://github.com/jasonmcintosh/rabbitmq-zabbix/blob/v2.0.1/rabbitmq.template.xml

See issue https://github.com/jasonmcintosh/rabbitmq-zabbix/issues/29 for more information.

**Comment by kommeht3d** [comment]
thank you!

**Comment by jasonmcintosh** [comment]
Closing :)  Open if you need more assistance!
