### ISSUE TITLE
Using certificate with SSL enabled.

### ISSUE THREAD

**Issue by darfadarfa** [jasonmcintosh/rabbitmq-zabbix#73]
Hi, I was wondering how I can pass a certificate with the request when SSL is enabled.

**Comment by jasonmcintosh** [comment]
Long story short (and then closing the issue) you can update the system store to either import the CA or the certificate.  On most linux systems it's in /etc/pki/* - but read system documentation for more information, or google 'python custom ssl certificate' and should find some links to assist you on where your system is reading it's location.
