### ISSUE TITLE
No data received on queue //aliveness-test in 10 minutes.

### ISSUE THREAD

**Issue by PDVJAM** [jasonmcintosh/rabbitmq-zabbix#75]
Hi! Sometimes I get this error and it seems that rabbitmq is OK at these times and it's something with zabbix/monitoring. Have you seen such an error or maybe you know what to check/how to fix this?

**Comment by jasonmcintosh** [comment]
Hrmm, not seen this personally.  COULD be concurrency issue on the agent side.  Wouldn't expect that but sorta grasping here.  Do any of the other queues/metrics not report data?  Server utilization numbers?  I'd lean towards something blocking the agent from delivering metric data.  That check is there in case the remote agent stops working or doesn't do it's job for some reason.

**Comment by PDVJAM** [comment]
Yep, maybe on the server side, I see this in logs:
`  9901:20170928:153610.119 In zbx_popen() command:'/srv/zabbix/libexec/rabbitmq-status.sh queues  '
  9901:20170928:153613.119 active check "rabbitmq[queues]" is not supported: Timeout while executing a shell script.
  9901:20170928:153613.119 In process_value() key:'cricketmgr.com:rabbitmq[queues]' value:'Timeout while executing a shell script.'
  9901:20170928:153613.169 JSON before sending [{"request":"agent data","data":[{"host":"cricketmgr.com","key":"rabbitmq[queues]","value":"Timeout while executing a shell script.","state":1,"clock":1506605773,"ns":119491547}],"clock":1506605773,"ns":169130145}]
`
But the rabbitmq check are the only have such an issue. Still investigating...

**Comment by jasonmcintosh** [comment]
That basically means the zabbix agent is taking too long to execute the checks.  This isn't the aliveness per se, but the entire set of queue checks.  This means that the script that queries rabbitmq via the mocha API's is taking too long.  Could be it ran out of memory, could be something else.  You SHOULD be able to enable logging in the agent, and have it log to a file of your choosing and see output.

**Comment by jasonmcintosh** [comment]
Note, zabbix agent has a default timeout for checks - e.g. 1 minute.  Though you'd have to really really really have a slow responses or something else going on to hit that timeout.  But can't rule it out.

**Comment by jasonmcintosh** [comment]
Closing this issue as been a while - feel free to re-open as needed :)  Would be curious to hear what you found out!

**Comment by probert-mtv** [comment]
We have a similar issue, same error message, but not the same message in Zabbix's server logs.

27031:20180329:081434.606 item "rabbitmqfed5-2:rabbitmq[queues]" became not supported: ZBX_NOTSUPPORTED
21069:20180329:082102.026 item "rabbitmqfed5-2:rabbitmq[queues]" became supported
