### ISSUE TITLE
rabbitmq.queues  in UserParameter of zabbix-rabbitmy.conf

### ISSUE THREAD

**Issue by samanahavemail** [jasonmcintosh/rabbitmq-zabbix#76]
i have question aboutt item 

rabbitmq.queues[vhost,queue_consumers,queuename ] that zabbix can discovery from your script// but i did not seen  Userparameter in zabbix-rabbitmq.conf 

https://www.dropbox.com/s/otmqh9v2ss1i5rx/Screenshot%202017-10-02%2015.29.57.png?dl=0

[root@csli-051-rabbitmq01 zabbix_agentd.d]# more zabbix-rabbitmq.conf
UserParameter=rabbitmq.discovery_queues,/etc/zabbix/scripts/rabbitmq/list_rabbit_queues.sh
UserParameter=rabbitmq.discovery_shovels,/etc/zabbix/scripts/rabbitmq/list_rabbit_shovels.sh
UserParameter=rabbitmq.discovery_nodes,/etc/zabbix/scripts/rabbitmq/list_rabbit_nodes.sh
UserParameter=rabbitmq[*],/etc/zabbix/scripts/rabbitmq/rabbitmq-status.sh $1 $2 $3

**Comment by jasonmcintosh** [comment]
It's not needed as the rabbitmq.queues items are all trap items and don't run on the agent via a User parameter.  Instead, the agent calls zabbix_sender to upload the items.

**Comment by samanahavemail** [comment]
pls explain me  more for "the agent calls zabbix_sender to upload the items"

**Comment by jasonmcintosh** [comment]
https://www.zabbix.com/documentation/3.4/manual/config/items/itemtypes/trapper
