### ISSUE TITLE
The data is not received on the zabbix

### ISSUE THREAD

**Issue by darksmoke** [jasonmcintosh/rabbitmq-zabbix#79]
good afternoon
I get an error     No data received on queue
in the broad gulls    2017-11-14 09:18:54,306 INFO: Found return code of 127

The data is not received on the zabbix, everything was done according to the instructions. Part of the data is there, and as far as the queue is concerned, there is no information on the number of messages.

**Comment by jasonmcintosh** [comment]
Likely an error on the server side - you can enable logging, look at logs and see what messages you get.  I'd guess a misconfiguration or something along those lines.  Would need more details to help debug.

**Comment by darksmoke** [comment]
2017-11-15 15:17:43,609 DEBUG: /bin/sh: zabbix_sender: command not found

how to specify your path?

**Comment by jasonmcintosh** [comment]
Should be on the path of your zabbix user - so typically it's bashrc or similar.  Make sure of course you have zabbix_sender installed - that SHOULD install it into a /usr/sbin or similar path that's generally part of the application.

**Comment by darksmoke** [comment]
I have a zabbix_sender installed. At installation I used not a standard way, I used --prefix=/opt/zabbix, so it is necessary to me. How can I specify my path to the zabbix_sender in your script?

**Comment by jasonmcintosh** [comment]
SO you can add /opt/zabbix to the zabbix user path or depending on how you startup the agent, add it to the path there.  OR symlink /usr/sbin/zabbix_sender to the one in /opt/zabbix OR ... this is really a linux question and there are many different ways to implement this.  You can also modify the api.py file to point the zabbix_sender to the right location.

**Comment by darksmoke** [comment]
I do not have root rights.
Tell me, please, in which line in the file to change the path to zabbix _sender?

**Comment by jasonmcintosh** [comment]
https://github.com/jasonmcintosh/rabbitmq-zabbix/blob/master/scripts/rabbitmq/api.py#L176

**Comment by darksmoke** [comment]
Thank you
I think it's good to put this in a separate parameter like

**Comment by jasonmcintosh** [comment]
Generally, this is the kinda stuff you'd do at the OS level vs. this level.  Could parameterize it at some point, though I've not seen a huge need yet for this.  But if you want to parameterize this with some sane defaults, feel free to implement it and create a pull request :)  In meantime, I figure I'll close this for now.
