### ISSUE TITLE
There's an issue at line 42 in the xml or at least many xml viewers have complained about this line

### ISSUE THREAD

**Issue by humartinez** [jasonmcintosh/rabbitmq-zabbix#83]
https://github.com/jasonmcintosh/rabbitmq-zabbix/blob/fe59d5a5c3d7cce3a0fdc2feb5f9b37eba498e05/rabbitmq.template.xml#L42

**Comment by jasonmcintosh** [comment]
I've validated the XML against w3's parsers.  The ability or inability of various XML Viewers to parse XML correctly isn't something I intend to work on.  If you find a specific bug feel free to report it.  I've tested this myself and had it work fine however.
