### ISSUE TITLE
Empty tmp* files being created in /tmp directory every minute

### ISSUE THREAD

**Issue by DSimmons2018** [jasonmcintosh/rabbitmq-zabbix#89]
Not sure if this is a configuration issue but I have been using the rabbitmq template from zabbix to monitor our rabbitmq server when a inodes error was generated. Noticed zabbix sender generating a blank tmp* file every minute. Had to disable sender until resolved. Any idea where to look or why empty tmp* files being generated every minute?

Thanks,
David

**Comment by jasonmcintosh** [comment]
SO the /tmp/files are supposedly the contents of queue status checks.  They're temporary files created in python and are SUPPOSED to be deleted after the checks finish.  
https://github.com/jasonmcintosh/rabbitmq-zabbix/blob/master/scripts/rabbitmq/api.py#L107
Is where these are created.  Unlink is supposed to remove them afterwards.

**Comment by ricohomewood** [comment]
I can confirm this is happening on my server too. Eventually the server will run out of spare inodes.

**Comment by jasonmcintosh** [comment]
Bleh had seen reports of this before but could never track it down exactly.  Wondering if it's a python bug.  See a ton of bug reports around NamedTemporaryFiles - so if anyone is good at python and debugging would welcome some assistance tracking this one down.

**Comment by jasonmcintosh** [comment]
Hrmm, digging through... wondering if this doesn't need to be os.remove() and ignore the close method... but this is where my python starts to fall down :(  SO if people want to try things and see if there's a solution, would love that!

**Comment by niakrisn** [comment]
Please check #92 PR

**Comment by jasonmcintosh** [comment]
Thanks @niakrisn approved & merged :)  @ricohomewood see if this fixes the issues?

**Comment by ricohomewood** [comment]
Thanks @jasonmcintosh and @niakrisn. I have applied this lasted fix and so far it is looking good.
