### ISSUE TITLE
Not getting data back - "rabbitmq.discovery_queues" became not supported

### ISSUE THREAD

**Issue by davkap92** [jasonmcintosh/rabbitmq-zabbix#91]
Hi Jason
Thanks for this plugin! Getting a bit stuck, so the aliveness check seems to be working fine but not getting anything back from any of the other checks such as number of messages in the queue etc. When I run the bash script in scripts/rabbitmq it works fine and brings back data

Found this in the zabbix server log:
`101406:20180615:093822.638 item "Fluffy1:rabbitmq.discovery_queues" became not supported: Unsupported item key.
101405:20180615:093827.654 item "Fluffy1:rabbitmq.discovery_shovels" became not supported: Unsupported item key.
101405:20180615:093827.654 item "Fluffy1:rabbitmq[queues]" became not supported: Unsupported item key.
101405:20180615:093827.654 item "Fluffy1:rabbitmq[server,disk_free]" became not supported: Unsupported item key.
101405:20180615:093827.654 item "Fluffy1:rabbitmq[server,fd_total]" became not supported: Unsupported item key.
101405:20180615:093827.654 item "Fluffy1:rabbitmq[server,fd_used]" became not supported: Unsupported item key.
101405:20180615:093827.654 item "Fluffy1:rabbitmq[server,mem_limit]" became not supported: Unsupported item key.
`

Not sure if this is a version compatibility issue? I'm using Zabbix 3.0.8
Thanks

**Comment by davkap92** [comment]
Also on the zabbix agent: 
`zabbix_agentd -t "rabbitmq[server,message_count_total]"` does appear working

**Comment by davkap92** [comment]
If any one else having this issue, I found changing items from  'Zabbix Agent(active)' to 'Zabbix Agent' worked...

**Comment by jasonmcintosh** [comment]
Awesome glad for that!  We've bounced back and forth between active and regular - different people use different setups.  I probably should update the docs with caution flags and a reminder "verify your behavior of active vs. passive zabbix checks" :)  Thanks!!

**Comment by jasonmcintosh** [comment]
Closing issue - reopen if needed :)

**Comment by SinghDivneet** [comment]
Hey , thanks for the plugin . 
Using the template zabbix 3.4 , for monitoring a rabbit mq cluster with a passive proxy . 
The only thing that is working for me is the aliveness test . 
Granted full access to `zabbix` user for all `vhost`  just in case in case I was missing something .

This is the only thing `Queue data status issue` on the zabbix console . Which doesn't leave me with a lot to forward

The weird thing is the log doesn't show any errors , so can't figure out where am  going wrong ?

The log is filled with just this : 
```2019-01-02 03:14:18,545 DEBUG: Started trying to process data
2019-01-02 03:14:18,546 DEBUG: Issue a rabbit API call to get data on aliveness-test/%2f against x.x.x.x
2019-01-02 03:14:18,546 DEBUG: Full URL:http://x.x.x.x:15672/api/aliveness-test/%2f
```

**Comment by jasonmcintosh** [comment]
Could be the same issue reported up above Active vs. Passive agent types - depends really heavily on your zabbix config for those kinds of issues.  Kudo's to @davkap92 for mentioning that earlier - just too often these kinds of things are monitoring config issues vs. code issues. I'm moving more and more to prometheus for monitoring vs. zabbix so I don't spend a huge amount of time on this stuff anymore :( .  You should be able to run the various checks as a zabbix user, run zabbix_get from the server, etc. to try and debug your environment.

**Comment by SinghDivneet** [comment]
Hey , thanks for the prompt response . 
Updated the agent to proxy .
So while running `zabbix_get` from the proxy instance works  , for some reason can't fetch the data to the zabbix server . 
@davkap92  is there something that is misconfigured ?

**Comment by SinghDivneet** [comment]
Or has something changed over the different zabbix agent versions ?

**Comment by jasonmcintosh** [comment]
SO that seems like an agent configuration issue - depends though on what message you're getting.  The zabbix agent itself is just a TCP listener on a port that then executes commands on a server (or delivers what's already loaded in the agent that's available without commands).  As such, it's likely a configuration setting either in agent or server on remote invocation allowance.  As I recall there were several settings to configure this on the zabbix agent.

**Comment by jasonmcintosh** [comment]
Note active vs. passive is more whether the agent runs the commands itself in a separate thread and "pushes" data back to the proxy/server OR whether the server/proxy sends requests for the data.  There's a mix of types in this project - including a different kind of "trap" style checks on the server that are expecting data.  There's one run job that triggers those checks.  Not to mention auto discovery rule based stuff.
