### ISSUE TITLE
error on import template

### ISSUE THREAD

**Issue by starlessboi** [jasonmcintosh/rabbitmq-zabbix#94]
Hi
when I want to import template to Zabbix (version 3.4), it shows error:
Graph prototype "Message rates on {#VHOSTNAME}/{#QUEUENAME}" contains item prototypes from multiple discovery rules.
can you tell me what can cause this problem.
thanks

**Comment by jasonmcintosh** [comment]
hrmm, somehow it's getting multiples of the same combination of vhost and queue name for the node.  Right now, not sure off top of my head... you should be able to run list_rabbit_queues.sh on the node, see what queues are reported.  I'll dig into this a bit see.  POSSIBLY ideas... cluster issue with different nodes reporting the same queue/vhost... though in theory those are supposed to be mastered on a single node.
